/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import "./globals.css";
import {Ubuntu} from "next/font/google"
import Header from "@/components/Header";
import {LanguageProvider} from "@/contex/LanguageContext"


const ubuntu  = Ubuntu({
  subsets: ["latin"],     // wajib, pilih subset
  weight: ["300", "400", "500","700"], // opsional, pilih bobot font
  variable: "--font-ubuntu", // opsional, pakai CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

        <link
          href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${ubuntu.className} antialiased`}
      >
        <LanguageProvider>
          <Header/>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
